spring:
  profiles:
    active: dev
  application:
    name: cacheTest
  data:
    redis:
      host: 106.75.216.143
      password: zzq
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/im
    username: root
    password: dugq123123
    driver-class-name: com.mysql.cj.jdbc.Driver
management: # springBoot actuator配置
  endpoints:
    web:
      base-path: /actuator #配置端点访问前缀
      exposure:
        include: '*'  #暴露所有端点
logging:
  level:
    org.hibernate.SQL: debug
debug: true
