spring:
    application:
        name: MongoDemo
    ai:
        openai:
            api-key: sk-1f63c8b93edd4cea8e50d313e59d9701
            base-url: https://api.deepseek.com
            chat:
                options:
                    model:
                        deepseek-chat
server:
    port: 8080
management: # springBoot actuator配置
    endpoints:
        web:
            base-path: /actuator #配置端点访问前缀
            exposure:
                include: '*'  #暴露所有端点
                exclude: info #在暴露所有端点的前提下，可以排除某个端点(不暴露)