server:
  port: 8080
spring:
  application:
    name: SpringBootLearning
management: # springBoot actuator配置
  endpoints:
    web:
      base-path: /actuator #配置端点访问前缀
      exposure:
        include: '*'  #暴露所有端点
        exclude: info #在暴露所有端点的前提下，可以排除某个端点(不暴露)
